### ISSUE TITLE
ImportError: /data/openfold/demo/GACT-ICML/gact/gact/cpp_extension/minimax.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPvmm

### ISSUE THREAD

**Issue by shunxing1234** [LiuXiaoxuanPKU/GACT-ICML#1]
```
>>> import gact
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/openfold/demo/GACT-ICML/gact/gact/__init__.py", line 1, in <module>
    from . import ops
  File "/data/openfold/demo/GACT-ICML/gact/gact/ops.py", line 8, in <module>
    import gact.cpp_extension.minimax as ext_minimax
ImportError: /data/openfold/demo/GACT-ICML/gact/gact/cpp_extension/minimax.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPvmm
```

When I call:
`python -m torch.utils.collect_env`
I get:
```
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-29-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB

Nvidia driver version: 470.86
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] pytorch-lightning==1.6.5
[pip3] torch==1.10.0+cu102
[pip3] torchaudio==0.10.0+rocm4.1
[pip3] torchmetrics==0.9.2
[pip3] torchvision==0.11.0+cu102
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] pytorch-lightning         1.6.5                    pypi_0    pypi
[conda] torch                     1.10.0+cu102             pypi_0    pypi
[conda] torchaudio                0.10.0+rocm4.1           pypi_0    pypi
[conda] torchmetrics              0.9.2                    pypi_0    pypi
[conda] torchvision               0.11.0+cu102             pypi_0    pypi
```

**Comment by LiuXiaoxuanPKU** [comment]
Thanks for the attention.
It seems the project is not built correctly. 
(1) Did you install GACT after installing 1.10 PyTorch? 
(2) after running `pip install -v -e` under gact, did you see the message `install gactxxxx successfully`?

**Comment by shunxing1234** [comment]
Hi @LiuXiaoxuanPKU thanks for ur reply, I reinstall the gact and it is working now!
BUT it seems didnot work in my code

```
from gact.controller import Controller # import gact controller
        import gact
        gact.set_optimization_level('L1')
        controller = Controller(model)
        controller.install_hook()
        for epoch in range(epochs):
            def backprop():
                target = torch.tensor([1.,0.]).to(self.device)
                x = torch.rand((1, 256, 256, 128)).to(self.device)
                mask = torch.randint(1, (1, 256, 256)).to(self.device)

                x =  model(x, mask, checkpoint=checkpoint, chunk_size=chunk_size, low_mem=low_mem).to(self.device)
                print('forward 0', torch.cuda.memory_allocated(device=0) / (1024 * 1024), 'MB')
                # print('forward 1', torch.cuda.memory_allocated(device=1) / (1024 * 1024), 'MB')
            
                loss = self.loss_fn(x, target)
            
                loss.backward()
                print('backward 0', torch.cuda.memory_allocated(device=0) / (1024 * 1024), 'MB')
                # print('backward 1', torch.cuda.memory_allocated(device=1) / (1024 * 1024), 'MB')
            
                self.optimizer.step()
            
                self.optimizer.zero_grad()

            controller.iterate(backprop)

        controller.uninstall_hook()

```
the backprop() func seems did not run

**Comment by LiuXiaoxuanPKU** [comment]
Right, you are running L1 optimization level, which will quantize all the layers uniformly with 4 bit and will not call backprop() to get the sensitivity of different layers.
If you want to adaptively change the bits for different layers (which will call backprop()), change `gact.set_optimization_level('L1')` to `gact.set_optimization_level('L2')`.

Please let me know if you meet any problems.

**Comment by shunxing1234** [comment]
I used L2 optimization level and got `GACT: Initializing AutoPrec..., run extra 0 iters` the backprop() func seems still not working

**Comment by LiuXiaoxuanPKU** [comment]
Could you post your model definition here, I will try to reproduce it.

**Comment by shunxing1234** [comment]
```
class TriangularAttentionblock(torch.nn.Module):
    def __init__(self, c_z, c, no_heads, starting) -> None:
        super(TriangularAttentionblock, self).__init__()
        self.attention = TriangleAttention(c_z, c, no_heads, starting)

        self.fc = nn.Linear(8388608, 2)

    def forward(self, 
        x: torch.Tensor, 
        mask: Optional[torch.Tensor] = None,
        chunk_size: Optional[int] = None,
        checkpoint: bool=False,
        low_mem: bool=False,
    ) -> torch.Tensor:

        attention_output = self.attention(x, mask, chunk_size, checkpoint=checkpoint, low_mem=low_mem)
        attention_output = attention_output.view(-1)
        fc_output = F.relu(self.fc(attention_output))

        return fc_output
```

**Comment by LiuXiaoxuanPKU** [comment]
Sorry for the late reply, did you solve the problem?
Some comments:
(1) you should not call `self.optimizer.step()` in the `backprop()`, because GACT does not want to update parameters when estimating the layer sensitivity.
(2) could you post the full execution scripts (including both model definition and training loop)?

**Comment by LiuXiaoxuanPKU** [comment]
Sorry for the late reply, I looked into your code a bit, and some comments here:
(1) please do not put `optimizer.step()` in `backprop()` function because GACT does not update the model parameters.
(2) please make sure your training loop is complete, which means it should include forward/backward/optimizer as the original training loop as follows:
```
for epoch in range(epochs):
        output = model(x, mask)
        def backdrop():
            optimizer.zero_grad()
            output =  model(x, mask).to(device)
            print('forward 0', torch.cuda.memory_allocated(device=0) / (1024 * 1024), 'MB')
            loss = (output - target).sum()
            loss.backward()
            print('backward 0', torch.cuda.memory_allocated(device=0) / (1024 * 1024), 'MB')

        loss = (output - target).sum()
        loss.backward()
        optimizer.step()
        
        controller.iterate(backprop)
```
(3) There is a `check_quantize` function to check if the saved tensor should be quantized or not. Code line: https://github.com/LiuXiaoxuanPKU/GACT-ICML/blob/52e6debb8146a4e14a6e11c67cb0582bb3c75ea4/gact/gact/quantizer.py#L47
You can add print statement in the function to check why a saved tensor is not quantized.

Please let me know if you have more questions.
